## 创建ndarray数组
### 基于`np.arange`

In [6]:
import numpy as np
#一维数组
arr1 = np.arange(5)
print(arr1)
#二维数组
arr2 = np.array([np.arange(5), np.arange(5)])
print(arr2)


[0 1 2 3 4]
[[0 1 2 3 4]
 [0 1 2 3 4]]


### 基于arange及reshape创建多维数组

In [7]:
import numpy as np
arr = np.arange(24).reshape(2, 3, 4)
print(arr)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


## `Numpy`的数值类型
具体的包括：
- `np.int8`
- `np.float64`
- `bool`
- `float`
- `complex`

In [3]:
import numpy as np
a = np.arange(5, dtype = float)
print(a)

[0. 1. 2. 3. 4.]


## ndarray数组的属性
- `dtype`：数据类型的种类
- `ndim`：数组维度的数量
- `shape`：数组对象的尺度，对于矩阵即n行m列，shape是一个元组
- `size`：用于保存元素的数量
- `itemsize`：返回数组中各个元素所占用的字节数大小
- `nbytes`: 返回整个数组所需的字节量
- `T`: 数组转置
- `real` `imag`：返回数组的实部、虚部
- `flat`：返回一个`numpy.flatiter`对象即可迭代的对象